### ISSUE TITLE
Contribution in videos section 📹

### ISSUE THREAD

**Issue by Alquimista3301** [fbdevelopercircles/FbDevcCommunityContent#32]
Hi everybody!
i would like to contribute in the video section adding some documentaries, but i don't know how it's the process, Can you help me ? 
Have a nice day 🐿

**Comment by aboullaite** [comment]
@Alquimista3301 i dont understand what do you mean by the "video section". Do you wanna be a guest in one of the episodes ?!

**Comment by Alquimista3301** [comment]
Nop, I meant to add this kind of content 👉 [GraphQL: The Documentary](https://bit.ly/2Xxu0c4)  in this section  👇
<img width="1713" alt="Captura de Pantalla 2020-04-13 a la(s) 17 34 35" src="https://user-images.githubusercontent.com/13058234/79167506-28782c80-7dad-11ea-8e98-c09668bf9c25.png">

**Comment by aboullaite** [comment]
Oh my bad, sorry for that! The process is very simple: initiate a pull request with the changes that you want to add! Once it gets accepted, it will be merged to the repo :)

Make sure to accept fb cla.

**Comment by aboullaite** [comment]
@Alquimista3301 do you have any other questions or we can close this issue ?

**Comment by Alquimista3301** [comment]
No, nothing else. Thank you :)
