### ISSUE TITLE
Add missing developer circles in DevCGlobalDirectory.md

### ISSUE THREAD

**Issue by vj-codes** [fbdevelopercircles/FbDevcCommunityContent#59]
The [DevCGlobalDirectory.md](https://github.com/fbdevelopercircles/FbDevcCommunityContent/blob/master/DevCGlobalDirectory.md)
 file does not include all Developer circles . I would like to document and add 5 missing developer circles in the file.

**Comment by vj-codes** [comment]
@tvalentius @BolajiAyodeji @saranshkataria I would like to work on this as a part of open source immersion, can you assign me please .
This will be my first contribution here yay!

**Comment by BolajiAyodeji** [comment]
Hi @vj-codes,

Thanks for wanting to make your first contribution. You're amazing!

The DevCGlobalDirectory file is not the official directory of all Facebook developer circles, you can find all [here](https://developers.facebook.com/developercircles/join/).

The file is community-curated, so feel free to send in a pull request to add any missing circle to the list.
Do let me know if you need any more help :)

Cheers!
